// Pinned ESPHome output is the scene compiler for BOTH targets. Export only
// allowlisted LVGL construction and font data; NEVER copy main.cpp or secrets.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import assert from "node:assert/strict";
const base = new URL("../", import.meta.url);
const generated = new URL("generated/", import.meta.url);
const build = new URL(".eve/esphome-build/owy-companion/src/", base);
const read = (name) => readFileSync(new URL(name, build), "utf8");
const hash = (s) => createHash("sha256").update(s).digest("hex");
// Never stamp current YAML hashes onto a stale generated scene. Compiler output
// may contain credentials, so keep all of it local and out of error messages.
const fresh = spawnSync("esphome", ["compile", "--only-generate", "owy-companion.yaml"], {
  cwd: fileURLToPath(new URL("firmware/", base)),
  encoding: "utf8",
  maxBuffer: 8 * 1024 * 1024,
});
assert(
  fresh.status === 0,
  "ESPHome source generation failed. Run it locally in firmware/ for diagnostics; no compiler output is exported."
);
const main = read("main.cpp");
assert(read("esphome/core/version.h").includes("2026.8.2"), "Scene compiler must be ESPHome 2026.8.2");
const start = main.indexOf("  new(companion_control) lv_style_t();");
const end = main.indexOf("  new(triggerlv_obj_tlv_point_tlv_event_t_id)", start);
assert(start > 0 && end > start, "Unknown scene boundaries: review new ESPHome generator");
const raw = main.slice(start, end);
assert(!/secret|password|staff_pin|api_key|wifi|noise_psk/i.test(raw));
let scene = raw.replace(/^\s*#line[^\n]*\n/gm, "").replaceAll("->obj", "");
scene = scene.replace(/new\((\w+)\) LvPageType\(false\);/g, "$1 = lv_obj_create(nullptr);");
scene = scene.replace(/^\s*ui->(?:add_page|set_page_wrap)\([^\n]+\n/gm, "");
scene = scene
  .replaceAll("ui->get_screen_active()", "lv_screen_active()")
  .replaceAll("ui->get_disp()", "lv_display_get_default()");
scene = scene.replace(/new\((\w+)\) Lv(?:Line|ButtonMatrix)Type\(\);/g, "");
scene = scene.replace(/(\w+)->set_obj\((lv_\w+\([^;]+)\);/g, "$1 = $2;");
scene = scene.replace(
  /(\w+)->set_points\((\{[^;]+)\);/g,
  "static const lv_point_precise_t $1_points[] = $2; lv_line_set_points($1, $1_points, 2);"
);
scene = scene.replace(/new\(companion_control\) lv_style_t\(\);/, "");
scene = scene.replace(/^\s*pin_k\w* = \d+;\n/gm, "");
// Fail closed if a new wrapper or side effect enters the construction block.
assert(!scene.includes("->") && !scene.includes("new("));
for (const line of scene
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean)) {
  assert(/^(lv_|\w+ = lv_|static const |[{}])/.test(line), `Unreviewed scene statement: ${line.slice(0, 100)}`);
}
const ids = [...scene.matchAll(/\b(\w+) = lv_\w+_create\(/g)].map((m) => m[1]);
const pages = ids.filter((id) => id.endsWith("_page"));
assert.equal(pages.length, 9);
const fonts = ["font_brand", "font_20", "font_28_bold", "font_40_bold"];
let data =
  '#pragma once\n// Generated bitmap data only. Montserrat: OFL; Organic Stencil: repository asset.\n#include "../font_adapter.h"\n';
const fontInit = [];
for (const name of fonts) {
  const args = main.match(new RegExp(`new\\(${name}\\) font::Font\\(([^;]+)\\);`))?.[1];
  assert(args, `Missing ${name}`);
  const glyphName = args.split(",")[0];
  const glyphs = main.match(new RegExp(`static const font::Glyph ${glyphName}\\[\\] = (\\{[^;]+);`))?.[1];
  assert(glyphs);
  const bitmap = glyphs.match(/\((uint8_t_id_\d+) \+/)?.[1];
  assert(bitmap);
  const declaration = main.match(
    new RegExp(`(?:static )?const(?:expr)? uint8_t ${bitmap}\\[\\](?: PROGMEM)? = (\\{[^;]+);`)
  )?.[1];
  assert(declaration, `Missing bitmap ${bitmap}`);
  assert(/^\{[\s,0-9A-Fa-fx]+\}$/.test(declaration), "Only literal bytes may leave firmware");
  data += `static const uint8_t ${bitmap}[] = ${declaration};\nstatic const font::Glyph ${glyphName}[] = ${glyphs};\n`;
  fontInit.push(
    `static font::Font ${name}_storage(${args});\nconst lv_font_t *${name} = ${name}_storage.get_lv_font();`
  );
}
data += fontInit.join("\n") + "\n";
const header = `#pragma once\n// Generated by ESPHome 2026.8.2, mechanically adapted for portable LVGL 9.5.\n#include "fonts.generated.h"\nnamespace owy {\nstruct Scene {\n${[...new Set(ids)].map((id) => `lv_obj_t *${id}{};`).join("\n")}\nlv_style_t control_storage{};\nlv_style_t *companion_control=&control_storage;\nvoid create() {\n${scene}\n}\nlv_obj_t *find(const char *name) {\n${[...new Set(ids)].map((id) => `if (!strcmp(name,"${id}")) return ${id};`).join("\n")}\nreturn nullptr;\n}\n};\n}\n`;
const sourceHashes = {};
for (const path of [
  "companion_model.h",
  "companion_motion.h",
  "companion_lvgl.h",
  "companion_sound.h",
  "packages/face.yaml",
  "packages/companion.yaml",
  "packages/voice.yaml",
  "packages/controls.yaml",
])
  sourceHashes[path] = hash(readFileSync(new URL(`firmware/${path}`, base)));
const manifest = {
  schema: 1,
  width: 466,
  height: 466,
  color: "RGB565",
  esphome: "2026.8.2",
  lvgl: "9.5.0",
  emscripten: "6.0.9",
  pages,
  objects: ids.length,
  sceneHash: hash(raw),
  fontsHash: hash(data),
  sourceHashes,
};
manifest.version = hash(JSON.stringify(manifest)).slice(0, 16);
mkdirSync(generated, { recursive: true });
writeFileSync(new URL("scene.generated.h", generated), header);
writeFileSync(new URL("fonts.generated.h", generated), data);
let conf = read("lv_conf.h").replace("LV_STDLIB_CUSTOM", "LV_STDLIB_CLIB");
conf = "#define LV_CONF_H\n#include <stdlib.h>\n#define LV_ASSERT_HANDLER abort();\n#define LV_LOG_PRINTF 1\n" + conf;
conf = conf.replace("#define LV_COLOR_16_SWAP 1", "#define LV_COLOR_16_SWAP 0");
writeFileSync(new URL("lv_conf.h", generated), conf);
writeFileSync(new URL("manifest.json", generated), JSON.stringify(manifest, null, 2) + "\n");
console.log(
  `Exported ${pages.length} pages, ${ids.length} objects, 4 exact font bitmaps. Version ${manifest.version}. No device configuration exported.`
);
